### ISSUE TITLE
KcpTun客户端

### ISSUE THREAD

**Issue by barryzzzzz** [hyird/openwrt-actions#9]
KcpTun客户端 打开错误代码

/usr/lib/lua/luci/dispatcher.lua:469: Failed to execute firstchild dispatcher target for entry '/admin/services/kcptun'.
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:469: Failed to execute cbi dispatcher target for entry '/admin/services/kcptun/settings'.
The called action terminated with an exception:
/usr/lib/lua/luci/cbi.lua:53: Model 'kcptun/settings' not found!
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:469: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>

**Comment by nicedayever** [comment]
之前同样遇到这个问题,后来 kcptun就没了

**Comment by hyird** [comment]
明天看看 哪个固件 仓库有俩
